<?php $_config_vars = array (
  'appliHome' => 'Accueil',
  'liToday' => 'Aujourd\'hui',
  'dayPrev' => 'Jour précédent',
  'dayNext' => 'Jour suivant',
  'theme' => 'Thème',
  'defaultTheme' => 'Thème de base',
  'or' => 'ou',
  'inpSubmit' => '<span class="accesskey">V</span>alider',
  'accSubmit' => 'v',
  'inpReset' => '<span class="accesskey">R</span>AZ',
  'accReset' => 'r',
  'inpEdit' => '<span class="accesskey">E</span>diter',
  'accEdit' => 'e',
  'titleEdit' => 'Éditer',
  'inpDelete' => '<span class="accesskey">S</span>upprimer',
  'accDelete' => 's',
  'labLogin' => '<span class="accesskey">L</span>ogin',
  'accLogin' => 'l',
  'labPassword' => '<span class="accesskey">M</span>ot de passe',
  'accPassword' => 'm',
  'labProject' => '<span class="accesskey">P</span>rojet',
  'accProject' => 'p',
  'noTask' => 'Aucune activité disponible',
  'labTask' => '<span class="accesskey">A</span>ctivité',
  'accTask' => 'a',
  'noProject' => 'Aucun projet disponible',
  'labShare' => 'Partager',
  'accShare' => 'p',
  'labUseInReport' => 'Utiliser dans les rapports',
  'accUseInReport' => 'u',
  'labRem' => 'Re<span class="accesskey">m</span>arque',
  'accRem' => 'm',
  'aProject' => 'Ajouter des projets',
  'aTask' => 'Ajouter des activités',
  'sillajHomepage' => 'Site de Sillaj',
  'xhtmlValid' => 'Site Valide XHTML 1.1',
  'cssValid' => 'Site valide CSS 3.0',
  'accessValid' => 'Accessibilité vérifiée',
  'for' => 'pour',
  'sumWorked' => 'Total',
  'project' => 'Projet',
  'task' => 'Activité',
  'labKeyword' => '<span class="accesskey">C</span>hercher',
  'accKeyword' => 'c',
  'aTitleTools' => 'Outils de gestion des données',
  'altTools' => 'Outils',
  'aGantt' => 'Diagramme de Gantt',
  'labName' => '<span class="accesskey">N</span>om',
  'accName' => 'n',
  'labFirstname' => '<span class="accesskey">P</span>rénom',
  'accFirstname' => 'p',
  'labEmail' => '<span class="accesskey">E</span>mail',
  'accEmail' => 'e',
  'notModifiedIfEmpty' => 'Non modifié si laissé vide',
  'editUser' => 'Modifier l\'utilisateur',
  'addUser' => 'Ajouter un utilisateur',
  'labAllowOther' => '<span class="accesskey">A</span>utoriser les autres utilisateurs à consulter mes rapports',
  'accAllowOther' => 'a',
  'labLanguage' => '<span class="accesskey">L</span>angue',
  'accLanguage' => 'l',
  'labTemplate' => 'M<span class="accesskey">o</span>dèle',
  'accTemplate' => 'o',
  'labUseShare' => '<span class="accesskey">U</span>tiliser les projets et activités partagés',
  'accUseShare' => 'u',
  'sendTo' => 'Envoyer à',
); ?>