<?php $_config_vars = array (
  'appliHome' => 'Home',
  'liToday' => 'Today',
  'dayPrev' => 'Previous day',
  'dayNext' => 'Next day',
  'theme' => 'Theme',
  'defaultTheme' => 'Default theme',
  'or' => 'or',
  'inpSubmit' => '<span class="accesskey">O</span>K',
  'accSubmit' => 'o',
  'inpReset' => '<span class="accesskey">R</span>eset',
  'accReset' => 'r',
  'inpEdit' => '<span class="accesskey">E</span>dit',
  'accEdit' => 'e',
  'titleEdit' => 'Éditer',
  'inpDelete' => '<span class="accesskey">D</span>elete',
  'accDelete' => 'd',
  'labLogin' => '<span class="accesskey">L</span>ogin',
  'accLogin' => 'l',
  'labPassword' => '<span class="accesskey">P</span>assword',
  'accPassword' => 'p',
  'labProject' => '<span class="accesskey">P</span>roject',
  'accProject' => 'p',
  'noTask' => 'No task available',
  'labTask' => 'Associated <span class="accesskey">T</span>ask',
  'accTask' => 't',
  'noProject' => 'No project available',
  'labRem' => 'Re<span class="accesskey">m</span>ark',
  'accRem' => 'm',
  'labShare' => 'Share',
  'accShare' => 's',
  'labUseInReport' => 'Use in reports',
  'accUseInReport' => 'u',
  'aTask' => 'Add tasks',
  'aProject' => 'Add projects',
  'sillajHomepage' => 'Go to sillaj home page',
  'xhtmlValid' => 'Valid XHTML 1.1',
  'cssValid' => 'Valid CSS 3.0',
  'accessValid' => 'Accessibility checked',
  'for' => 'for',
  'project' => 'Project',
  'task' => 'Task',
  'sumWorked' => 'Sum',
  'labKeyword' => 'Se<span class="accesskey">a</span>rch',
  'accKeyword' => 'a',
  'aTitleTools' => 'Data management tools',
  'altTools' => 'Tools',
  'aGantt' => 'Gantt graph',
  'aTitleTask' => 'Go to the task manager',
  'editProject' => 'Edit a project',
  'addProject' => 'Add a project',
  'aEventForProject' => 'Events',
  'aTitleEventForProject' => 'Events for this project',
  'aTitleGanttForProject' => 'Gantt graph for this projet',
); ?>